In [1]:
import numpy as np
from scipy import ndimage
from skimage.measure import regionprops, label
from rasterio import features
from pprint import pprint

In [2]:
a = np.zeros((6,6), dtype=np.int)
a[2:4, 2:4] = 1
a[4,4] = 1
a[:2, :3] = 2
a[0, 5] = 3
a[4:6, 2:4] = 5
a[2:3, 0:1] = 8
a[3:5, 1:2] = 8
a[5:6, 0:1] = 8

In [3]:
a

array([[2, 2, 2, 0, 0, 3],
       [2, 2, 2, 0, 0, 0],
       [8, 0, 1, 1, 0, 0],
       [0, 8, 1, 1, 0, 0],
       [0, 8, 5, 5, 1, 0],
       [8, 0, 5, 5, 0, 0]])

### This is what regionprops does

In [48]:
slices = ndimage.find_objects(a)
for i, s in enumerate(slices):
    print("Slice # " + str(i) + ": " + str(s))

Slice # 0: (slice(2, 5, None), slice(2, 5, None))
Slice # 1: (slice(0, 2, None), slice(0, 3, None))
Slice # 2: (slice(0, 1, None), slice(5, 6, None))
Slice # 3: None
Slice # 4: (slice(4, 6, None), slice(2, 4, None))
Slice # 5: None
Slice # 6: None
Slice # 7: (slice(2, 6, None), slice(0, 2, None))


In [49]:
props = regionprops(a)
for p in props:
    print("Object " + str(p.label) + " has " + str(p.area) + " pixels.")

Object 1 has 5 pixels.
Object 2 has 6 pixels.
Object 3 has 1 pixels.
Object 5 has 4 pixels.
Object 8 has 4 pixels.


### This is what rasterio features.shapes does

In [50]:
# connectivity is ROOK style...connectivity = 4
shps = features.shapes(a.astype(np.int32))
shapes = list(shps)
print("The length of the list is: " + str(len(shapes)) + "\n")
for s in shapes:
    print(s)

The length of the list is: 12

({'type': 'Polygon', 'coordinates': [[(0.0, 0.0), (0.0, 2.0), (3.0, 2.0), (3.0, 0.0), (0.0, 0.0)]]}, 2.0)
({'type': 'Polygon', 'coordinates': [[(5.0, 0.0), (5.0, 1.0), (6.0, 1.0), (6.0, 0.0), (5.0, 0.0)]]}, 3.0)
({'type': 'Polygon', 'coordinates': [[(0.0, 2.0), (0.0, 3.0), (1.0, 3.0), (1.0, 2.0), (0.0, 2.0)]]}, 8.0)
({'type': 'Polygon', 'coordinates': [[(1.0, 2.0), (1.0, 3.0), (2.0, 3.0), (2.0, 2.0), (1.0, 2.0)]]}, 0.0)
({'type': 'Polygon', 'coordinates': [[(2.0, 2.0), (2.0, 4.0), (4.0, 4.0), (4.0, 2.0), (2.0, 2.0)]]}, 1.0)
({'type': 'Polygon', 'coordinates': [[(0.0, 3.0), (0.0, 5.0), (1.0, 5.0), (1.0, 3.0), (0.0, 3.0)]]}, 0.0)
({'type': 'Polygon', 'coordinates': [[(1.0, 3.0), (1.0, 5.0), (2.0, 5.0), (2.0, 3.0), (1.0, 3.0)]]}, 8.0)
({'type': 'Polygon', 'coordinates': [[(2.0, 4.0), (2.0, 6.0), (4.0, 6.0), (4.0, 4.0), (2.0, 4.0)]]}, 5.0)
({'type': 'Polygon', 'coordinates': [[(4.0, 4.0), (4.0, 5.0), (5.0, 5.0), (5.0, 4.0), (4.0, 4.0)]]}, 1.0)
({'type': 'Poly

In [51]:
# connectivity is QUEEN style...connectivity = 8
shps = features.shapes(a.astype(np.int32), connectivity=8)
shapes = list(shps)
print("The length of the list is: " + str(len(shapes)) + "\n")
for s in shapes:
    print(s)

The length of the list is: 7

({'type': 'Polygon', 'coordinates': [[(0.0, 0.0), (0.0, 2.0), (3.0, 2.0), (3.0, 0.0), (0.0, 0.0)]]}, 2.0)
({'type': 'Polygon', 'coordinates': [[(3.0, 0.0), (3.0, 2.0), (4.0, 2.0), (4.0, 4.0), (5.0, 4.0), (5.0, 5.0), (4.0, 5.0), (4.0, 6.0), (5.0, 6.0), (6.0, 6.0), (6.0, 1.0), (5.0, 1.0), (5.0, 0.0), (3.0, 0.0)]]}, 0.0)
({'type': 'Polygon', 'coordinates': [[(5.0, 0.0), (5.0, 1.0), (6.0, 1.0), (6.0, 0.0), (5.0, 0.0)]]}, 3.0)
({'type': 'Polygon', 'coordinates': [[(0.0, 2.0), (0.0, 3.0), (1.0, 3.0), (1.0, 5.0), (0.0, 5.0), (0.0, 6.0), (1.0, 6.0), (1.0, 5.0), (2.0, 5.0), (2.0, 3.0), (1.0, 3.0), (1.0, 2.0), (0.0, 2.0)]]}, 8.0)
({'type': 'Polygon', 'coordinates': [[(1.0, 2.0), (1.0, 3.0), (0.0, 3.0), (0.0, 5.0), (1.0, 5.0), (1.0, 6.0), (2.0, 6.0), (2.0, 5.0), (1.0, 5.0), (1.0, 3.0), (2.0, 3.0), (2.0, 2.0), (1.0, 2.0)]]}, 0.0)
({'type': 'Polygon', 'coordinates': [[(2.0, 2.0), (2.0, 4.0), (4.0, 4.0), (4.0, 5.0), (5.0, 5.0), (5.0, 4.0), (4.0, 4.0), (4.0, 2.0), (2.0, 

###### *Above, there are 2 background polygons (polygons with 0s)

### Now...what if I 'label' the image

In [52]:
a # a is still the same as before

array([[2, 2, 2, 0, 0, 3],
       [2, 2, 2, 0, 0, 0],
       [8, 0, 1, 1, 0, 0],
       [0, 8, 1, 1, 0, 0],
       [0, 8, 5, 5, 1, 0],
       [8, 0, 5, 5, 0, 0]])

In [59]:
b = np.copy(a) # b is a copy of a, but with 9s instead of 0s.
b[b==0] = 9
b

array([[2, 2, 2, 9, 9, 3],
       [2, 2, 2, 9, 9, 9],
       [8, 9, 1, 1, 9, 9],
       [9, 8, 1, 1, 9, 9],
       [9, 8, 5, 5, 1, 9],
       [8, 9, 5, 5, 9, 9]])

In [60]:
labeled = label(b, connectivity=2)  # connectivity is QUEEN style
#labeled = label(b, connectivity=1)  # connectivity is ROOK style

In [61]:
labeled

array([[1, 1, 1, 2, 2, 3],
       [1, 1, 1, 2, 2, 2],
       [4, 5, 6, 6, 2, 2],
       [5, 4, 6, 6, 2, 2],
       [5, 4, 7, 7, 6, 2],
       [4, 5, 7, 7, 2, 2]])

In [62]:
slices = ndimage.find_objects(labeled)
for i, s in enumerate(slices):
    print("Slice # " + str(i) + ": " + str(s))

Slice # 0: (slice(0, 2, None), slice(0, 3, None))
Slice # 1: (slice(0, 6, None), slice(3, 6, None))
Slice # 2: (slice(0, 1, None), slice(5, 6, None))
Slice # 3: (slice(2, 6, None), slice(0, 2, None))
Slice # 4: (slice(2, 6, None), slice(0, 2, None))
Slice # 5: (slice(2, 5, None), slice(2, 5, None))
Slice # 6: (slice(4, 6, None), slice(2, 4, None))


In [63]:
props = regionprops(labeled)
for p in props:
    print("Object " + str(p.label) + " has " + str(p.area) + " pixels.")

Object 1 has 6 pixels.
Object 2 has 12 pixels.
Object 3 has 1 pixels.
Object 4 has 4 pixels.
Object 5 has 4 pixels.
Object 6 has 5 pixels.
Object 7 has 4 pixels.


##### Now with features.shapes

In [67]:
# connectivity is QUEEN style...connectivity = 8
shps = features.shapes(b.astype(np.int32), connectivity=8)
shapes = list(shps)
print("The length of the list is: " + str(len(shapes)) + "\n")
for s in shapes:
    print(s)

The length of the list is: 7

({'type': 'Polygon', 'coordinates': [[(0.0, 0.0), (0.0, 2.0), (3.0, 2.0), (3.0, 0.0), (0.0, 0.0)]]}, 2.0)
({'type': 'Polygon', 'coordinates': [[(3.0, 0.0), (3.0, 2.0), (4.0, 2.0), (4.0, 4.0), (5.0, 4.0), (5.0, 5.0), (4.0, 5.0), (4.0, 6.0), (5.0, 6.0), (6.0, 6.0), (6.0, 1.0), (5.0, 1.0), (5.0, 0.0), (3.0, 0.0)]]}, 9.0)
({'type': 'Polygon', 'coordinates': [[(5.0, 0.0), (5.0, 1.0), (6.0, 1.0), (6.0, 0.0), (5.0, 0.0)]]}, 3.0)
({'type': 'Polygon', 'coordinates': [[(0.0, 2.0), (0.0, 3.0), (1.0, 3.0), (1.0, 5.0), (0.0, 5.0), (0.0, 6.0), (1.0, 6.0), (1.0, 5.0), (2.0, 5.0), (2.0, 3.0), (1.0, 3.0), (1.0, 2.0), (0.0, 2.0)]]}, 8.0)
({'type': 'Polygon', 'coordinates': [[(1.0, 2.0), (1.0, 3.0), (0.0, 3.0), (0.0, 5.0), (1.0, 5.0), (1.0, 6.0), (2.0, 6.0), (2.0, 5.0), (1.0, 5.0), (1.0, 3.0), (2.0, 3.0), (2.0, 2.0), (1.0, 2.0)]]}, 9.0)
({'type': 'Polygon', 'coordinates': [[(2.0, 2.0), (2.0, 4.0), (4.0, 4.0), (4.0, 5.0), (5.0, 5.0), (5.0, 4.0), (4.0, 4.0), (4.0, 2.0), (2.0, 

### Let's try this with an skewed image...

In [125]:
i = np.zeros((10, 10), dtype=np.int64)
# center
i[2:6, 2:5] = 1
i[2:6, 5:8] = 2
i[6:8, 2:5] = 3
i[5:6, 3:5] = 3
i[6:8, 5:8] = 4
i[4:6, 5:6] = 4
i[4:5, 4:5] = 4
# left
i[7:8, 0:2] = 5
i[4:7, 1:2] = 5
i[3:4, 1:2] = 5
i[2:3, 2:3] = 5
# bottom
i[8:10, 7:8] = 6
i[8:9, 4:7] = 6
# right
i[2:3, 8:10] = 7
i[3:6, 8:9] = 7
i[4:6, 9:10] = 7
# bottom
i[0:2, 2:3] = 8
i[1:2, 3:6] = 8
i[1:2, 2:3] = 1

In [126]:
i

array([[0, 0, 8, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 8, 8, 8, 0, 0, 0, 0],
       [0, 0, 5, 1, 1, 2, 2, 2, 7, 7],
       [0, 5, 1, 1, 1, 2, 2, 2, 7, 0],
       [0, 5, 1, 1, 4, 4, 2, 2, 7, 7],
       [0, 5, 1, 3, 3, 4, 2, 2, 7, 7],
       [0, 5, 3, 3, 3, 4, 4, 4, 0, 0],
       [5, 5, 3, 3, 3, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 6, 6, 6, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 6, 0, 0]])

In [127]:
mask = np.zeros((10, 10), dtype=np.int64)
# center
mask[2:8, 2:8] = 1
# left
mask[7:8, 0:2] = 1
mask[4:7, 1:2] = 1
# bottom
mask[8:10, 7:8] = 1
mask[8:9, 4:7] = 1
# right
mask[2:3, 8:10] = 1
mask[3:6, 8:9] = 1
# bottom
mask[0:2, 2:3] = 1
mask[1:2, 3:6] = 1

In [128]:
mask

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0]])

In [129]:
output = i * mask
output

array([[0, 0, 8, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 8, 8, 8, 0, 0, 0, 0],
       [0, 0, 5, 1, 1, 2, 2, 2, 7, 7],
       [0, 0, 1, 1, 1, 2, 2, 2, 7, 0],
       [0, 5, 1, 1, 4, 4, 2, 2, 7, 0],
       [0, 5, 1, 3, 3, 4, 2, 2, 7, 0],
       [0, 5, 3, 3, 3, 4, 4, 4, 0, 0],
       [5, 5, 3, 3, 3, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 6, 6, 6, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 6, 0, 0]])

In [140]:
sieved = features.sieve(output.astype('int32'), 2, mask=mask.astype('uint8'), connectivity=8)
sieved

array([[0, 0, 8, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 8, 8, 8, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 2, 2, 2, 7, 7],
       [0, 0, 1, 1, 1, 2, 2, 2, 7, 0],
       [0, 5, 1, 1, 4, 4, 2, 2, 7, 0],
       [0, 5, 1, 3, 3, 4, 2, 2, 7, 0],
       [0, 5, 3, 3, 3, 4, 4, 4, 0, 0],
       [5, 5, 3, 3, 3, 4, 4, 4, 0, 0],
       [0, 0, 0, 0, 6, 6, 6, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 6, 0, 0]], dtype=int32)

In [143]:
output - sieved

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])